
package com.rit.bookstore.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookStore", targetNamespace = "http://services.bookstore.rit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookStore {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.rit.bookstore.services.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByTitle", targetNamespace = "http://services.bookstore.rit.com/", className = "com.rit.bookstore.services.GetBookByTitle")
    @ResponseWrapper(localName = "getBookByTitleResponse", targetNamespace = "http://services.bookstore.rit.com/", className = "com.rit.bookstore.services.GetBookByTitleResponse")
    @Action(input = "http://services.bookstore.rit.com/BookStore/getBookByTitleRequest", output = "http://services.bookstore.rit.com/BookStore/getBookByTitleResponse")
    public Book getBookByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.rit.bookstore.services.Book
     */
    @WebMethod(operationName = "BookDetailsByAuthor")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BookDetailsByAuthor", targetNamespace = "http://services.bookstore.rit.com/", className = "com.rit.bookstore.services.BookDetailsByAuthor")
    @ResponseWrapper(localName = "BookDetailsByAuthorResponse", targetNamespace = "http://services.bookstore.rit.com/", className = "com.rit.bookstore.services.BookDetailsByAuthorResponse")
    @Action(input = "http://services.bookstore.rit.com/BookStore/BookDetailsByAuthorRequest", output = "http://services.bookstore.rit.com/BookStore/BookDetailsByAuthorResponse")
    public Book bookDetailsByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
