
package com.rit.bookstore.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookStoreImplService", targetNamespace = "http://services.bookstore.rit.com/", wsdlLocation = "http://localhost:8080/WS/BookLine?wsdl")
public class BookStoreImplService
    extends Service
{

    private final static URL BOOKSTOREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSTOREIMPLSERVICE_EXCEPTION;
    private final static QName BOOKSTOREIMPLSERVICE_QNAME = new QName("http://services.bookstore.rit.com/", "BookStoreImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/BookLine?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSTOREIMPLSERVICE_WSDL_LOCATION = url;
        BOOKSTOREIMPLSERVICE_EXCEPTION = e;
    }

    public BookStoreImplService() {
        super(__getWsdlLocation(), BOOKSTOREIMPLSERVICE_QNAME);
    }

    public BookStoreImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSTOREIMPLSERVICE_QNAME, features);
    }

    public BookStoreImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSTOREIMPLSERVICE_QNAME);
    }

    public BookStoreImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSTOREIMPLSERVICE_QNAME, features);
    }

    public BookStoreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookStoreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookStore
     */
    @WebEndpoint(name = "BookStoreImplPort")
    public BookStore getBookStoreImplPort() {
        return super.getPort(new QName("http://services.bookstore.rit.com/", "BookStoreImplPort"), BookStore.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookStore
     */
    @WebEndpoint(name = "BookStoreImplPort")
    public BookStore getBookStoreImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.bookstore.rit.com/", "BookStoreImplPort"), BookStore.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSTOREIMPLSERVICE_EXCEPTION!= null) {
            throw BOOKSTOREIMPLSERVICE_EXCEPTION;
        }
        return BOOKSTOREIMPLSERVICE_WSDL_LOCATION;
    }

}
